### ISSUE TITLE
OAuth login

### ISSUE THREAD

**Issue by montanaflynn** [basicallydan/forkability#55]
In the README.md it mentions the following:

>https://basicallydan.github.io/forkability runs the code in its client-side form (works just fine), but it requires you to log in using GitHub OAuth. It will ask for access to write to your profile, which I promise will not be exploited. This is merely a limitation of Firebase. You can't ask for no scope.

However I had no issue running my public projects without logging in. Is the requirement for running private repos? Is it a legacy requirement?

**Comment by basicallydan** [comment]
Hi Montana thanks for bringing this up.

You're right that it isn't a requirement for forkability in general. It *is* a requirement for private repos, but you'll also be given autocomplete when you log in.

So, the wording is incorrect, basically :) I can fix that!

**Comment by basicallydan** [comment]
@montanaflynn I made a mistake this morning when I said that: that's not the reason. Sorry, it's been a while since I touched that code. It is just in fact a legacy requirement.

I did also notice that the oauth is a liiiittle bit broken right now. Something's wrong with the oauth auth server I built for GitHub login to work. So now I gotta fix that.

Anyway, I'll sort out that readme now.

**Comment by basicallydan** [comment]
Alrighty then, done!
