### ISSUE TITLE
Add shrinkwrap to the makefile

### ISSUE THREAD

**Issue by M-Zuber** [basicallydan/forkability#76]
Steps to implement:
- Fork the repo
- Update the [makefile](https://github.com/basicallydan/forkability/blob/master/makefile)
 - [ ] Add a `shrinkwrap` command with value of: `rm -rf node_modules/ npm-shrinkwrap.json && npm install && npm shrinkwrap`
 - [ ] Add `@echo "  shrinkwarp        resets the shrinkwrap.json file"` to the `help` command
- Make sure it runs, and [open a PR](https://github.com/basicallydan/forkability/compare)

That's it and welcome to open source :grinning: :tada:

**Comment by basicallydan** [comment]
Great first timers only! You've probably already considered this but I do have a small concern.

Do we definitely want this in the `deps` task? It means whenever someone clones and runs `deps` they're potentially making a change to the repo, potentially a chance to the code and therefore potentially a change to functionality. This would defeat essentially the object of shrinkwrap - keeping the code exactly the same for a particular commit.

This is definitely useful, but we need to ensure people don't clone then immediately do this when all they wanna do is reproduce and track down a bug which may well be caused by a specific version of a dependency.

See what I mean? Or am I missing something?

**Comment by M-Zuber** [comment]
:100: 
I've updated the issue accordingly.
We need to update the documentation to include a mention of the makefile btw

**Comment by basicallydan** [comment]
Yeah you're right we do. I can do that quickly no prob!

Good update - I can get fully behind this! :)

**Comment by Charlotteis** [comment]
Hello! Gonna twoot bout this from @youfirstpr today! Thanks so much for making things.

**Comment by M-Zuber** [comment]
Thank you. What time are you tweeting as I may have some more for you :wink:

**Comment by Charlotteis** [comment]
I only do one a day, but as my next one would be on Christmas day I could do a bonus round. Tweets usually go out at 1PM :)

**Comment by M-Zuber** [comment]
I will try and have it ready by then :)

**Comment by basicallydan** [comment]
Ahhhh so much activity. I will find a coffee shop and try to help :P

**Comment by basicallydan** [comment]
Thank you @Charlotteis for the ol' tweetage :)

**Comment by Charlotteis** [comment]
Think this can be closed now :)

**Comment by basicallydan** [comment]
Yes! Thanks Charlotte!

See you some time at some event in London I hope!

**Comment by M-Zuber** [comment]
So it should be closed then? :stuck_out_tongue_closed_eyes:

**Comment by basicallydan** [comment]
Haha sorry I thought Charlotte had closed it too!

--Dan
danhough.com <http://www.danhough.com> - @basicallydan
<http://twitter.com/basicallydan>

**Comment by Charlotteis** [comment]
I don't have those permissions!
